### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by iemejia** [iemejia/catho#31]
When indexing really long volumes

**Comment by iemejia** [comment]
an alternative is to measure the size of the files collection and add it in batches to the database
probably using generators would be also a nice trick.

**Comment by iemejia** [comment]
or fix a number for batches also

**Comment by iemejia** [comment]
Maybe a more elegant solution exists but this works for the moment.

**Comment by iemejia** [comment]
the exception is still going on:

Python(15742) malloc: **\* mmap(size=140645843243008) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "catho/catho.py", line 303, in <module>
    for files in filesubsets:
  File "catho/catho.py", line 77, in file_get_filelist
    hash = file_hash(fullpath, hash_type)
  File "catho/catho.py", line 50, in file_hash
    sha1.update(f.read())
MemoryError

**Comment by iemejia** [comment]
Actually this is a different issue, see issue #32
